//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindFilmFree.Application {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_de {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_de() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FindFilmFree.Application.Resources.Language_de", typeof(Language_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string congratulationMember {
            get {
                return ResourceManager.GetString("congratulationMember", resourceCulture);
            }
        }
        
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        internal static string usersCount {
            get {
                return ResourceManager.GetString("usersCount", resourceCulture);
            }
        }
        
        internal static string activeUsersCount {
            get {
                return ResourceManager.GetString("activeUsersCount", resourceCulture);
            }
        }
        
        internal static string deactiveUsersCount {
            get {
                return ResourceManager.GetString("deactiveUsersCount", resourceCulture);
            }
        }
        
        internal static string writeYourMessage {
            get {
                return ResourceManager.GetString("writeYourMessage", resourceCulture);
            }
        }
        
        internal static string hiMsg {
            get {
                return ResourceManager.GetString("hiMsg", resourceCulture);
            }
        }
        
        internal static string startMsg {
            get {
                return ResourceManager.GetString("startMsg", resourceCulture);
            }
        }
        
        internal static string registered {
            get {
                return ResourceManager.GetString("registered", resourceCulture);
            }
        }
        
        internal static string sent_messages {
            get {
                return ResourceManager.GetString("sent_messages", resourceCulture);
            }
        }
        
        internal static string nameAdded {
            get {
                return ResourceManager.GetString("nameAdded", resourceCulture);
            }
        }
        
        internal static string numberAdded {
            get {
                return ResourceManager.GetString("numberAdded", resourceCulture);
            }
        }
        
        internal static string addFilmName {
            get {
                return ResourceManager.GetString("addFilmName", resourceCulture);
            }
        }
        
        internal static string linkAdded {
            get {
                return ResourceManager.GetString("linkAdded", resourceCulture);
            }
        }
        
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        internal static string chooseLanguage {
            get {
                return ResourceManager.GetString("chooseLanguage", resourceCulture);
            }
        }
        
        internal static string refLink {
            get {
                return ResourceManager.GetString("refLink", resourceCulture);
            }
        }
        
        internal static string friendsCount {
            get {
                return ResourceManager.GetString("friendsCount", resourceCulture);
            }
        }
        
        internal static string sentMessage {
            get {
                return ResourceManager.GetString("sentMessage", resourceCulture);
            }
        }
        
        internal static string languageChanged {
            get {
                return ResourceManager.GetString("languageChanged", resourceCulture);
            }
        }
        
        internal static string subscribe_to_the_channel {
            get {
                return ResourceManager.GetString("subscribe_to_the_channel", resourceCulture);
            }
        }
        
        internal static string check_your_subscription {
            get {
                return ResourceManager.GetString("check_your_subscription", resourceCulture);
            }
        }
        
        internal static string subscribePls {
            get {
                return ResourceManager.GetString("subscribePls", resourceCulture);
            }
        }
        
        internal static string numbernotexist {
            get {
                return ResourceManager.GetString("numbernotexist", resourceCulture);
            }
        }
        
        internal static string defaultMsg {
            get {
                return ResourceManager.GetString("defaultMsg", resourceCulture);
            }
        }
    }
}
